# Generated by Django 2.1.1 on 2018-09-29 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('deletedAt', models.DateTimeField(blank=True)),
                ('licencePlate', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('deletedAt', models.DateTimeField(blank=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('seatCount', models.IntegerField()),
                ('internet', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('powerOutlet', models.BooleanField(default=False)),
                ('tablet', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='busType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_info.BusType'),
        ),
        migrations.AddField(
            model_name='bus',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
